DB_HOST: "localhost"
DB_USER: "postgres"
DB_PASSWORD: "postgres"
DB_NAME: "dailybrewdb"

JWT_SECRET: "your-secret-key"

SERVER_PORT: "8080"
REDIS_HOST: "localhost"
REDIS_PORT: "6379"
REDIS_PASSWORD: ""